ARG REGISTRY=""
FROM ${REGISTRY}node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

# Production environment
FROM nginx:1.29.5-alpine3.23
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]